name: CI with Maven and Horusec

on:
  push:
    branches: [ "main", "feature/Horusec" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Install Horusec CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s "v2.9.0-beta.3"

      - name: Run Horusec (no fail)
        run: |
          horusec start -p="./" \
            -c="horusec-config.json" \
            --return-error=false \
            --json-output-file="horusec-report.json"

      - name: Gate on HIGH/CRITICAL
        run: |
          CRIT=$(jq '[.analysisVulnerabilities[].vulnerabilities.severity | select(.=="CRITICAL")] | length' horusec-report.json)
          HIGH=$(jq '[.analysisVulnerabilities[].vulnerabilities.severity | select(.=="HIGH")] | length' horusec-report.json)
          echo "Found CRITICAL=$CRIT HIGH=$HIGH"
          if [ "$CRIT" -gt 0 ] || [ "$HIGH" -gt 0 ]; then
            echo "High or Critical vulnerabilities found!"
            exit 1
          fi

      - name: Upload Horusec report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: horusec-report
          path: horusec-report.json
